// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID          pgtype.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Version     int32
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Name         string
	CountryCode  pgtype.Text
	PhoneNumber  pgtype.Text
	Address      pgtype.Text
	PasswordHash []byte
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	Version      int32
}
